export const djs = [
  'ac slater',
  'acraze',
  'alleycvt',
  'armin van buuren',
  'avao',
  'bunt',
  'celo',
  'the chainsmokers',
  'chase & status',
  'cheyenne giles',
  'claptone',
  'dave summer',
  'diesel (shaquille o-neal)',
  'dog eat dog (crankdat x riot ten)',
  'domeno',
  'draeden',
  'ferry corsten presents gouryella',
  'fisher',
  'ganja white night',
  'gg magree',
  'goodboys',
  'gorillat',
  'hairitage',
  'hamro',
  'hugel',
  'ilan bluestone',
  'illenium',
  'imanu b2b nitepunk',
  'isoxo',
  'james hype',
  'kayzo',
  'knock2',
  'kream',
  'kyle walker',
  'lev3l',
  'levity',
  'lost frequencies',
  'lucas & steve',
  'maddix',
  'matt sassari',
  'mau p',
  'max styler',
  'merow',
  'michael sparks',
  'morten',
  'niiko x swae',
  'no thanks',
  'noizu',
  'oddkidout',
  'pretty pink',
  'return of the jaded',
  'sammi virji',
  'seven lions',
  'slander',
  'steve angello',
  'steve aoki',
  'subtronics',
  'tape b',
  'tchami x malaa (no redemption)',
  'vini vici',
  'zedd',
  'zubah',
];

export const supportDjs = [
  'dersed',
  'ecco & sando',
  'filthy',
  'karl k-otik',
  'kiari',
  'marta',
  'mholy',
  'mvngo',
  'oly west b2b igluu',
  'pineo & loeb',
  'sammy',
  'setou & senyo',
  'vanpage',
  'zabo',
];
